//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int Id { get; set; }
        public string KullaniciAd { get; set; }
        public string Parola { get; set; }
        public Nullable<int> YetkiId { get; set; }
    
        public virtual yetki yetki { get; set; }
    }
}
